name: organization_pgp
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+11

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  shared_preferences: ^2.2.2
  pinput: ^3.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  percent_indicator: ^4.2.3
  android_package_installer:
    git:
      url: https://github.com/ImranR98/android_package_installer
      ref: main
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  pinch_zoom_image_last: ^0.4.1
  easy_image_viewer: ^1.4.0
  url_launcher: ^6.2.3
  photo_view: ^0.14.0
  pull_to_refresh: ^2.0.0
  share_plus: ^7.2.1
  appinio_video_player: ^1.2.2
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  flutter_animate: ^4.4.0
  lottie: ^2.7.0
  persian_utils: ^2.0.1
  sms_otp_auto_verify: ^2.1.0
  file_picker: ^6.1.1
  universal_html: ^2.2.4
  persian_datetime_picker: ^2.6.0
  persian_linear_date_picker: ^0.0.2
  flutter_adaptive_ui: ^0.8.0+1
  syncfusion_flutter_pdfviewer: ^24.1.45
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  loading_animation_widget: ^1.2.0+4
  toastification: ^1.1.0
  gap: ^3.0.1
  dotted_dashed_line: ^0.0.3
  image_picker: ^1.0.7
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  firebase_core: ^2.24.2
  open_filez: ^4.1.5
  pdfx:
    git:
      url: https://github.com/bahiraei/pdfx.git
      ref: main





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
#  flutter_app_name: ^0.1.1



flutter_app_name:
  name: "اپ سازمانی"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/bipc_launcher2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/auth/
    - assets/images/home/
    - assets/images/birthday/
    - assets/images/profile/
    - assets/images/calendar/
    - assets/images/meeting/
    - assets/images/feedback/-+
    -


  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/iransans/regular.ttf
          weight: 400
        - asset: assets/fonts/iransans/black.ttf
          weight: 900
        - asset: assets/fonts/iransans/light.ttf
          weight: 300
        - asset: assets/fonts/iransans/ultraLight.ttf
          weight: 200
        - asset: assets/fonts/iransans/bold.ttf
          weight: 700
        - asset: assets/fonts/iransans/medium.ttf
          weight: 500


